# Generated by Django 4.2.5 on 2025-03-22 19:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Pending Review', 'Pending Review'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('category', models.CharField(choices=[('Pothole', 'Pothole'), ('Lighting', 'Lighting'), ('Fly-tipping', 'Fly-tipping'), ('Blocked Drain', 'Blocked Drain'), ('Graffiti', 'Graffiti'), ('Anti-Social Behaviour', 'Anti-Social Behaviour'), ('Other', 'Other')], default='Other', max_length=30)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_attention', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issue_images/')),
                ('risk_level', models.IntegerField(blank=True, help_text='Risk level from 1 to 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('related_issues', models.ManyToManyField(blank=True, related_name='related_to', to='issues.issue')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='issues_issu_status_bea796_idx'), models.Index(fields=['created_at'], name='issues_issu_created_6f38eb_idx'), models.Index(fields=['priority'], name='issues_issu_priorit_77f54b_idx')],
            },
        ),
    ]
