# Generated by Django 4.2.5 on 2025-03-23 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issues_issu_priorit_77f54b_idx',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='related_issues',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='requires_attention',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='tags',
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('roads', 'Roads & Infrastructure'), ('environment', 'Environment'), ('safety', 'Community Safety'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
